(function() {

    var TRACKJS = [
        '<!-- BEGIN TRACKJS -->\n',
        '<script type="text/javascript">window._trackJs = { token: \'6faf671244264572a4f8cd794dc51d78\' };</script>\n',
        '<script type="text/javascript" src="https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js"></script>\n',
        '<!-- END TRACKJS -->\n'].join('');

    var GOOGLE_ANALYTICS = [
        "<!-- Google Analytics Tracking Code -->",
        "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){",
        "(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),",
        "m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)",
        "})(window,document,'script','//www.google-analytics.com/analytics.js','ga');",
        "ga('create', 'UA-22813809-2', 'auto');ga('send', 'pageview');</script>",
        "<!-- End of Google Analytics -->\n"].join('');

    var CORE_JS = [ // the script filenames, paths are relative to HTML page, in dependency order
        "js/seadragon/seadragon-dev.js",
        "js/thirdparty/bowser.min.js",
        "data/projectdata.js",
        "js/jquery/jquery-1.11.1.min.js",
        "js/jquery/jquery.resizeStop.js",
        "js/jquery/jqueryui/1.10.4/js/jquery-ui-1.10.4.custom.min.js",
        "js/jsinheritance.js",
        "js/fibics/language/lang.controller.js",
        "js/fibics/language/lang.english.js",
        "js/fibics/language/lang.french.js",
        "js/fibics/language/lang.german.js",
        "js/fibics/utils.js",
        "js/application.js",
        "js/normalizedevents.js",
        "js/md5.js",
        "js/jalert.js",
        "js/mobile.js",
        "js/fibics/common/common.changecounted.js",
        "js/fibics/common/fibics.geometry.js",
        "js/fibics/fibics.project.js",
        "js/fibics/controller.message.js",
        "js/fibics/ui/ui.messagepanel.js",
        "js/fibics/fibics.slideshowcontroller.js",
        "js/fibics/fibics.exportedinstance.js",
        "js/fibics/controller.basecontroller.js",
        "js/fibics/common/xmlutils.js",
        "js/fibics/fibics.basescalebar.js",
        "js/fibics/fibics.scalebar.js",
        "js/fibics/fibics.scalebaroncanvas.js",
        "js/fibics/session.serializer.js",
        "js/jquery/jquery.cookie.js",
        "js/jquery/jquery.ui.touch-punch.min.js",
        "js/jquery/jquery.hittest.js",
        "js/jquery/jquery.parseparams.js",
        "js/fibics/io.storage.js",
        "js/jquery/jquery.tipsy.js",
        "js/jquery/alphanumeric/jquery.alphanumeric.pack.js",
        "js/jquery/jquery-minicolors-master/jquery.minicolors.js",
        "js/jquery/loadingdotdotdot/js/jquery.loadingdotdotdot.js",
        "js/json2.js",
        "js/json2xml.js",
        "js/keyboard.js",
        "js/xml2json.js",
        "js/rgbcolor.js",
        "js/fibics/ui/ui.element.js",
        "js/fibics/blending.blendingcontroller.js",
        "js/fibics/blending.blendinginfo.js",
        "js/fibics/ui/ui.blendinginfo.js",
        "js/fibics/ui/ui.slideshowinfobar.js",
        "js/fibics/ui/ui.scalebarfixedwidthform.js",
        "js/fibics/utils.debug.js",
        "js/fibics/dimension.js",
        "js/fibics/common/common.uid.js",
        "js/fibics/geometry.js",
        "js/fibics/crosshair.js",
        "js/fibics/seadragonimagegenerator.js",
        "js/fibics/measurement/display.measurementcontroller.js",
        "js/fibics/waypoint/display.waypointcontroller.js",
        "js/fibics/measurement/display.anchorpoint.js",
        "js/fibics/measurement/display.node.js",
        "js/fibics/measurement/measurement.js",
        "js/fibics/measurement/measurement.withcaption.js",
        "js/fibics/measurement/measurement.serializer.js",
        "js/fibics/measurement/display.measurement.js",
        "js/fibics/measurement/measurement.line.js",
        "js/fibics/measurement/region.region.js",
        "js/fibics/measurement/display.line.js",
        "js/fibics/measurement/measurement.caption.js",
        "js/fibics/measurement/display.caption.js",
        "js/fibics/measurement/measurement.textannotation.js",
        "js/fibics/measurement/display.textannotation.js",
        "js/fibics/measurement/measurement.simplemeasurement.js",
        "js/fibics/measurement/display.simplemeasurement.js",
        "js/fibics/measurement/measurement.longmeasurement.js",
        "js/fibics/measurement/display.longmeasurement.js",
        "js/fibics/measurement/measurement.protractor.js",
        "js/fibics/measurement/display.protractor.js",
        "js/fibics/measurement/measurement.rectangulararea.js",
        "js/fibics/measurement/display.rectangulararea.js",
        "js/fibics/measurement/measurement.ellipticalarea.js",
        "js/fibics/measurement/display.ellipticalarea.js",
        "js/fibics/measurement/measurement.ruler.js",
        "js/fibics/measurement/display.ruler.js",
        "js/fibics/measurement/measurement.exporttopng.js",
        "js/fibics/measurement/display.exporttopng.js",
        "js/fibics/measurement/measurement.polygon.js",
        "js/fibics/measurement/region.polygon.js",
        "js/fibics/measurement/region.ellipse.js",
        "js/fibics/measurement/region.rectangle.js",
        "js/fibics/measurement/region.regioneditor.js",
        "js/fibics/measurement/display.polygonalregion.js",
        "js/fibics/measurement/measurement.polygonalarea.js",
        "js/fibics/measurement/measurement.controller.js",
        "js/fibics/waypoint/waypoint.js",
        "js/fibics/view/view.controller.js",
        "js/fibics/view/view.atlasview.js",
        "js/fibics/view/view.serializer.js",
        "js/fibics/ui/widget.atlasview.js",
        "js/fibics/waypoint/display.waypoint.js",
        "js/fibics/waypoint/waypointcontroller.js",
        "js/fibics/waypoint/waypoint.serializer.js",
        "js/fibics/ui/widget.basewidget.js",
        "js/fibics/ui/ui.sidebarwidget.js",
        "js/fibics/ui/widget.exportinfo.js",
        "js/fibics/ui/ui.applicationsettingsform.js",
        "js/fibics/ui/ui.editviewform.js",
        "js/fibics/ui/ui.magcalibrationform.js",
        "js/fibics/ui/ui.saveimageform.js",
        "js/fibics/ui/widget.measurement.js",
        "js/fibics/ui/widget.debugpanel.js",
        "js/fibics/ui/widget.language.js",
        "js/fibics/ui/widget.waypoint.js",
        "js/fibics/ui/widget.atlasinfo.js",
        "js/fibics/ui/widget.distancetable.js",
        "js/fibics/ui/widget.savedata.js",
        "js/fibics/ui/widget.blending.js",
        "js/fibics/ui/widget.slideshow.js",
        "js/fibics/ui/ui.loadingpage.js",
        "js/fibics/ui/ui.dockarea.js",
        "js/fibics/utils.canvasBlender.js",
        "js/fibics/ui/widget.viewportmodecontrol.js",
        "js/fibics/ui/ui.textannotationeditform.js",
        "js/fibics/ui/ui.measurementlengtheditform.js",
        "js/fibics/ui/ui.measurementareaeditform.js",
        "js/fibics/ui/widget.zoompancontrols.js",
        "js/fibics/ui/widget.overview.js",
        "js/fibics/fibics.atlasviewport.js",
        "js/fibics/fibics.seadragonconverter.js",
        "js/fibics/fibics.atlasviewportcontroller.js",
        "js/fibics/DistanceTable.js",
        "js/fibics/TestEvents.js",
        "js/fibics/ui/widget.viewportinfo.js",
        "js/fibics/ui/ui.footer.js",
        "js/fibics/manager.layout.js",
        "js/fibics/keyboardcontroller.js",
        "js/fibics/fibics.browsercheck.js",
        "js/application.settings.js",
        "js/fibics/fibics.cursor.js",
        "debug/mesxml.js",
        "js/fibics/utils.graphics.js",
        "js/thirdparty/chart.min.js",
        "js/fibics/ui/ui.histogram.js",
        "js/fibics/common/common.strutils.js",
        "js/thirdparty/hammer.2.0.6.min.js",
        "js/fibics/common/common.graphicutils.js",
        "js/fibics/waypoint/display.text.js",
        "js/fibics/ui.worldcoordpanel.js",
        "js/thirdparty/paper-full.min.js",
        "js/thirdparty/filesaver.js",
        "js/fibics/ui/museumofnature/ui.languageswitcher.js",
        "js/fibics/ui/museumofnature/splashscreentimeout.js",
        "js/loadonready.js"
    ];
    var html = [];

    html.push(TRACKJS); //comment out to disable TRACKJS
    //html.push(GOOGLE_ANALYTICS); //un-comment to enable GOOGLE_ANALYTICS

    for (var i = 0; i < CORE_JS.length; i++) {
        html.push('<script type="text/javascript" src="');
        html.push(CORE_JS[i]);
        html.push('"></script>\n');
    }

    // "defer" attr is needed here otherwise IE executes this too early
    //html.push('<script type="text/javascript" defer="defer">\nG_DEBUG = true;\n</script>\n'); //comment out to disable debug-mode

    document.write(html.join(''));
})();
